version: 0.2

env:
  variables:
    TF_VAR_db_master_username: "dbadmin"
    TF_VAR_db_master_password: "StrongPass123"
    TF_VERSION:      "1.7.1"
    TF_WORKING_DIR:  "environments/dev"
    TF_STATE_BUCKET: "dr-demo-use1-east-37cfd18a"
    TF_STATE_KEY:    "env/terraform.tfstate"
    TF_STATE_REGION: "us-east-1"
    APPLY:           "false"

cache:
  paths:
    - "~/.terraform.d/plugin-cache/**"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -sSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o /tmp/terraform.zip
      - unzip -oq /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - cd "$TF_WORKING_DIR"
      - terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=${TF_STATE_KEY}" \
          -backend-config="region=${TF_STATE_REGION}"

  build:
    commands:
      - terraform fmt -recursive
      - terraform fmt -check
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands: |
      if [ "$APPLY" = "true" ]; then
        terraform apply -auto-approve tfplan
      else
        echo "Apply skipped (APPLY=false)"
      fi

artifacts:
  base-directory: "$TF_WORKING_DIR"
  files:
    - tfplan
  discard-paths: yes
