version: 0.2

env:
  variables:
    TF_VERSION:        "1.7.1"                # pin Terraform
    TF_WORKING_DIR:    "environments/dev"     # folder that contains main.tf
    TF_STATE_BUCKET:   "dr-tf-state-e1"       # remote state bucket (primary region)
    TF_STATE_KEY:      "dev/terraform.tfstate"
    TF_STATE_REGION:   "us-east-1"
    APPLY:             "false"                # set to "true" to run terraform apply

cache:
  paths:
    - "~/.terraform.d/plugin-cache/**"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -sSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o /tmp/terraform.zip
      - unzip -oq /tmp/terraform.zip -d /usr/local/bin
      - terraform -version
  pre_build:
    commands:
      - cd "$TF_WORKING_DIR"
      - terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=${TF_STATE_KEY}" \
          -backend-config="region=${TF_STATE_REGION}"
  build:
    commands:
      - terraform fmt -check
      - terraform validate
      - terraform plan -out=tfplan
  post_build:
    commands:
      - |
        if [ "$APPLY" = "true" ]; then
          terraform apply -auto-approve tfplan
        else
          echo "Skip apply (APPLY=false)"
        fi

artifacts:
  files:
    - "$TF_WORKING_DIR/tfplan"
  discard-paths: yes
